
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PhongFPT
 */
public class AddCourse extends javax.swing.JDialog {

    /**
     * Creates new form AddCourse
     */
    CourseManagement parent;
    public AddCourse(java.awt.Frame parent, String title) {
        super(parent, title);
        initComponents();
        this.setLocationRelativeTo(null);
        this.parent=(CourseManagement)parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAddCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddName = new javax.swing.JTextField();
        lbWarningAddCode = new javax.swing.JLabel();
        lbWarningAddName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddCredit = new javax.swing.JTextField();
        lbWarningAddCredit = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btClear = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Code");

        txtAddCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddCodeMouseClicked(evt);
            }
        });

        jLabel3.setText("Name");

        txtAddName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddNameMouseClicked(evt);
            }
        });

        lbWarningAddCode.setForeground(new java.awt.Color(204, 0, 51));

        lbWarningAddName.setForeground(new java.awt.Color(204, 0, 51));

        jLabel6.setText("Credit");

        txtAddCredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddCreditMouseClicked(evt);
            }
        });

        lbWarningAddCredit.setForeground(new java.awt.Color(204, 0, 51));

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addGap(27, 27, 27)
                        .addComponent(btClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddCode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddName, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtAddCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbWarningAddCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbWarningAddName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbWarningAddCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbWarningAddCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbWarningAddName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWarningAddCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btClear))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        
        String code=txtAddCode.getText().trim();
        String name=txtAddName.getText().trim();
        String credit=txtAddCredit.getText().trim();
        if(isValidation(code, name, credit)){
            name=name.toLowerCase();
            name=name.substring(0,1).toUpperCase()+name.substring(1);
            parent.getCourseList().add(new Course(code, name, credit));
            JOptionPane.showMessageDialog(this, "Add successful");
            hideLabelWaring();
            txtAddCode.setText("");
            txtAddName.setText("");
            txtAddCredit.setText("");
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void txtAddCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddCodeMouseClicked
        // TODO add your handling code here:
        lbWarningAddCode.setText("");
    }//GEN-LAST:event_txtAddCodeMouseClicked

    private void txtAddNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddNameMouseClicked
        // TODO add your handling code here:
        lbWarningAddName.setText("");
    }//GEN-LAST:event_txtAddNameMouseClicked

    private void txtAddCreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddCreditMouseClicked
        // TODO add your handling code here:
        lbWarningAddCredit.setText("");
    }//GEN-LAST:event_txtAddCreditMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        txtAddCode.setText("");
        txtAddName.setText("");
        txtAddCredit.setText("");
        hideLabelWaring();
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    boolean isValidation(String code, String name, String credit) {
        //Code: can’t be empty, can’t be duplicated
        boolean isValidation=true;
        if(code.isEmpty()){
            lbWarningAddCode.setText("Code can't be empty");
            isValidation=false;
        }else if(findCourseByCode(code)!=null){
            lbWarningAddCode.setText("Code is existed");
            isValidation=false;
        }
        //Name can’t be empty
        if(name.isEmpty()){
            lbWarningAddName.setText("Name can't be empty");
            isValidation=false;
        }
        //credit can't be empty
        if(credit.isEmpty()){
            lbWarningAddCredit.setText("Credit can't be empty");
            isValidation=false;
        }
        //Credit must be a positive number and less than or equals to 33.
        else{
            try {
                int creditInteger=Integer.parseInt(credit);
                if(creditInteger<0){
                    lbWarningAddCredit.setText("Credit must be a positive number");
                    isValidation=false;
                }else if(creditInteger>33){
                    lbWarningAddCredit.setText("Credit must be less than or equals to 33");
                    isValidation=false;
                }
            } catch (NumberFormatException e) {
                lbWarningAddCredit.setText("Credit must be a positive number, less than or equals to 33");
                isValidation=false;
            }
        } 
            
       return isValidation;    
    }

    Course findCourseByCode(String code) {
        ArrayList<Course> courseList=parent.getCourseList();
        Course courseSearch=null;
        for (Course course : courseList) {
            if(course.getCode().equalsIgnoreCase(code)){
                courseSearch=course;
                break;
            }
        }
        return courseSearch;
    }
    void hideLabelWaring(){
        lbWarningAddCode.setText("");
        lbWarningAddName.setText("");
        lbWarningAddCredit.setText("");
    }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AddCourse dialog = new AddCourse(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbWarningAddCode;
    private javax.swing.JLabel lbWarningAddCredit;
    private javax.swing.JLabel lbWarningAddName;
    private javax.swing.JTextField txtAddCode;
    private javax.swing.JTextField txtAddCredit;
    private javax.swing.JTextField txtAddName;
    // End of variables declaration//GEN-END:variables
}
